services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./crm-tg-app-postgress/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 20s


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-local
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/pgadmin-servers.json:/pgadmin4/servers.json:ro


  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey-local
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - valkey_data:/data

    command: >
      valkey-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

  crm-tg-app:
    build:
      context: ./crm-tg-app
      dockerfile: Dockerfile
    container_name: crm-tg-app
    volumes:
      - ./crm-tg-app:/app
      - crm-tg-app-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER=1
      - CHOKIDAR_USEPOLLING=true

  crm-tg-app-backend:
    build:
      context: ./crm-tg-app-backend
      dockerfile: Dockerfile
    container_name: crm-tg-app-backend
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_started
    volumes:
      - ./crm-tg-app-backend:/app
      - crm-tg-app-backend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_NAME=app
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - crm-tg-app
      - crm-tg-app-backend


volumes:
  postgres_data:
  pgadmin_data:
  valkey_data:
  crm-tg-app-node-modules:
  crm-tg-app-backend-node-modules:
